CreateOrderLambdaFunctionQualifiedArn = "arn:aws:lambda:us-east-1:605122994140:function:fencify-graphql-api-backend-dev-createOrder:5"
CreateContractLambdaFunctionQualifiedArn = "arn:aws:lambda:us-east-1:605122994140:function:fencify-graphql-api-backend-dev-createContract:3"
WebCognitoUserPoolClientId = "1kv8012m8818kf70322dqrfoj3"
CreateProductLambdaFunctionQualifiedArn = "arn:aws:lambda:us-east-1:605122994140:function:fencify-graphql-api-backend-dev-createProduct:2"
ConfirmUserSignupLambdaFunctionQualifiedArn = "arn:aws:lambda:us-east-1:605122994140:function:fencify-graphql-api-backend-dev-confirmUserSignup:4"
CreateEstimatorLambdaFunctionQualifiedArn = "arn:aws:lambda:us-east-1:605122994140:function:fencify-graphql-api-backend-dev-createEstimator:2"
CreateInstallationTermLambdaFunctionQualifiedArn = "arn:aws:lambda:us-east-1:605122994140:function:fencify-graphql-api-backend-dev-createInstallationTerm:2"
ServerlessDeploymentBucketName = "fencify-graphql-api-back-serverlessdeploymentbuck-1cumshxh8k8nw"
CreateCustomerLambdaFunctionQualifiedArn = "arn:aws:lambda:us-east-1:605122994140:function:fencify-graphql-api-backend-dev-createCustomer:2"
CognitoUserPoolId = "us-east-1_lJmt0bbQI"
AwsRegion = "us-east-1"
CreateEstimateLambdaFunctionQualifiedArn = "arn:aws:lambda:us-east-1:605122994140:function:fencify-graphql-api-backend-dev-createEstimate:5"
FencifygraphqlapiGraphQlApiId = "72htd7lqknfrzm27db4okj6le4"
CreateJobCostLambdaFunctionQualifiedArn = "arn:aws:lambda:us-east-1:605122994140:function:fencify-graphql-api-backend-dev-createJobCost:2"
CreateQuoteLambdaFunctionQualifiedArn = "arn:aws:lambda:us-east-1:605122994140:function:fencify-graphql-api-backend-dev-createQuote:6"
CreateUserLambdaFunctionQualifiedArn = "arn:aws:lambda:us-east-1:605122994140:function:fencify-graphql-api-backend-dev-createUser:2"
FencifygraphqlapiGraphQlApiUrl = "https://jm7kl2bbhzbhjgy7wp7mz7q7li.appsync-api.us-east-1.amazonaws.com/graphql"